/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import Foundation

// taptaptap 3e: Swift port of the constants in FBiOSTargetConfiguration.h/.m. Names are the former
// NS_ENUM / NS_STRING_ENUM Swift spellings; raw values are copied verbatim from the .m.

/// Uses the known values of SimDeviceType ProductFamilyID, to construct an enumeration.
/// These mirror the values from -[SimDeviceState productFamilyID].
@objc public enum FBControlCoreProductFamily: UInt {
  case familyUnknown = 0
  case familyiPhone = 1
  case familyiPad = 2
  case familyAppleTV = 3
  case familyAppleWatch = 4
  case familyMac = 5
}

/// Device Names Enumeration.
public struct FBDeviceModel: RawRepresentable, Hashable, Sendable {
  public let rawValue: String

  public init(rawValue: String) {
    self.rawValue = rawValue
  }

  public static let modeliPhone4s = FBDeviceModel(rawValue: "iPhone 4s")
  public static let modeliPhone5 = FBDeviceModel(rawValue: "iPhone 5")
  public static let modeliPhone5c = FBDeviceModel(rawValue: "iPhone 5c")
  public static let modeliPhone5s = FBDeviceModel(rawValue: "iPhone 5s")
  public static let modeliPhone6 = FBDeviceModel(rawValue: "iPhone 6")
  public static let modeliPhone6Plus = FBDeviceModel(rawValue: "iPhone 6 Plus")
  public static let modeliPhone6S = FBDeviceModel(rawValue: "iPhone 6s")
  public static let modeliPhone6SPlus = FBDeviceModel(rawValue: "iPhone 6s Plus")
  public static let modeliPhoneSE_1stGeneration = FBDeviceModel(rawValue: "iPhone SE (1st generation)")
  public static let modeliPhoneSE_2ndGeneration = FBDeviceModel(rawValue: "iPhone SE (2nd generation)")
  public static let modeliPhone7 = FBDeviceModel(rawValue: "iPhone 7")
  public static let modeliPhone7Plus = FBDeviceModel(rawValue: "iPhone 7 Plus")
  public static let modeliPhone8 = FBDeviceModel(rawValue: "iPhone 8")
  public static let modeliPhone8Plus = FBDeviceModel(rawValue: "iPhone 8 Plus")
  public static let modeliPhoneX = FBDeviceModel(rawValue: "iPhone X")
  public static let modeliPhoneXs = FBDeviceModel(rawValue: "iPhone Xs")
  public static let modeliPhoneXsMax = FBDeviceModel(rawValue: "iPhone Xs Max")
  public static let modeliPhoneXr = FBDeviceModel(rawValue: "iPhone Xʀ")
  public static let modeliPhone11 = FBDeviceModel(rawValue: "iPhone 11")
  public static let modeliPhone11Pro = FBDeviceModel(rawValue: "iPhone 11 Pro")
  public static let modeliPhone11ProMax = FBDeviceModel(rawValue: "iPhone 11 Pro Max")
  public static let modeliPhone12mini = FBDeviceModel(rawValue: "iPhone 12 mini")
  public static let modeliPhone12 = FBDeviceModel(rawValue: "iPhone 12")
  public static let modeliPhone12Pro = FBDeviceModel(rawValue: "iPhone 12 Pro")
  public static let modeliPhone12ProMax = FBDeviceModel(rawValue: "iPhone 12 Pro Max")
  public static let modeliPhone13mini = FBDeviceModel(rawValue: "iPhone 13 mini")
  public static let modeliPhone13 = FBDeviceModel(rawValue: "iPhone 13")
  public static let modeliPhone13Pro = FBDeviceModel(rawValue: "iPhone 13 Pro")
  public static let modeliPhone13ProMax = FBDeviceModel(rawValue: "iPhone 13 Pro Max")
  public static let modeliPhone14 = FBDeviceModel(rawValue: "iPhone 14")
  public static let modeliPhone14Plus = FBDeviceModel(rawValue: "iPhone 14 Plus")
  public static let modeliPhone14Pro = FBDeviceModel(rawValue: "iPhone 14 Pro")
  public static let modeliPhone14ProMax = FBDeviceModel(rawValue: "iPhone 14 Pro Max")
  public static let modeliPhone15 = FBDeviceModel(rawValue: "iPhone 15")
  public static let modeliPhone15Plus = FBDeviceModel(rawValue: "iPhone 15 Plus")
  public static let modeliPhone15Pro = FBDeviceModel(rawValue: "iPhone 15 Pro")
  public static let modeliPhone15ProMax = FBDeviceModel(rawValue: "iPhone 15 Pro Max")
  public static let modeliPhone16 = FBDeviceModel(rawValue: "iPhone 16")
  public static let modeliPhone16Plus = FBDeviceModel(rawValue: "iPhone 16 Plus")
  public static let modeliPhone16Pro = FBDeviceModel(rawValue: "iPhone 16 Pro")
  public static let modeliPhone16ProMax = FBDeviceModel(rawValue: "iPhone 16 Pro Max")
  public static let modeliPhone16e = FBDeviceModel(rawValue: "iPhone 16e")
  public static let modeliPhone17 = FBDeviceModel(rawValue: "iPhone 17")
  public static let modeliPhone17Pro = FBDeviceModel(rawValue: "iPhone 17 Pro")
  public static let modeliPhone17ProMax = FBDeviceModel(rawValue: "iPhone 17 Pro Max")
  public static let modeliPodTouch_7thGeneration = FBDeviceModel(rawValue: "iPod touch (7th generation)")
  public static let modeliPad2 = FBDeviceModel(rawValue: "iPad 2")
  public static let modeliPad_6thGeneration = FBDeviceModel(rawValue: "iPad (6th generation)")
  public static let modeliPad_7thGeneration = FBDeviceModel(rawValue: "iPad (7th generation)")
  public static let modeliPad_8thGeneration = FBDeviceModel(rawValue: "iPad (8th generation)")
  public static let modeliPad_9thGeneration = FBDeviceModel(rawValue: "iPad (9th generation)")
  public static let modeliPad_10thGeneration = FBDeviceModel(rawValue: "iPad (10th generation)")
  public static let modeliPadRetina = FBDeviceModel(rawValue: "iPad Retina")
  public static let modeliPadA16 = FBDeviceModel(rawValue: "iPad (A16)")
  public static let modeliPadAir = FBDeviceModel(rawValue: "iPad Air")
  public static let modeliPadAir2 = FBDeviceModel(rawValue: "iPad Air 2")
  public static let modeliPadAir_3rdGeneration = FBDeviceModel(rawValue: "iPad Air (3rd generation)")
  public static let modeliPadAir_4thGeneration = FBDeviceModel(rawValue: "iPad Air (4th generation)")
  public static let modeliPadPro = FBDeviceModel(rawValue: "iPad Pro")
  public static let modeliPadPro_9_7_Inch = FBDeviceModel(rawValue: "iPad Pro (9.7-inch)")
  public static let modeliPadPro_12_9_Inch = FBDeviceModel(rawValue: "iPad Pro (12.9-inch)")
  public static let modeliPadPro_9_7_Inch_2ndGeneration = FBDeviceModel(rawValue: "iPad Pro (9.7-inch) (2nd generation)")
  public static let modeliPadPro_12_9_Inch_2ndGeneration = FBDeviceModel(rawValue: "iPad Pro (12.9-inch) (2nd generation)")
  public static let modeliPadPro_12_9_Inch_3rdGeneration = FBDeviceModel(rawValue: "iPad Pro (12.9-inch) (3rd generation)")
  public static let modeliPadPro_12_9_Inch_4thGeneration = FBDeviceModel(rawValue: "iPad Pro (12.9-inch) (4th generation)")
  public static let modeliPadPro_10_5_Inch = FBDeviceModel(rawValue: "iPad Pro (10.5-inch)")
  public static let modeliPadPro_11_Inch_1stGeneration = FBDeviceModel(rawValue: "iPad Pro (11-inch) (1st generation)")
  public static let modeliPadPro_12_9nch_1stGeneration = FBDeviceModel(rawValue: "iPad Pro (12.9-inch) (1st generation)")
  public static let modeliPadPro_11_Inch_2ndGeneration = FBDeviceModel(rawValue: "iPad Pro (11-inch) (2nd generation)")
  public static let modeliPadMini_2 = FBDeviceModel(rawValue: "iPad mini 2")
  public static let modeliPadMini_3 = FBDeviceModel(rawValue: "iPad mini 3")
  public static let modeliPadMini_4 = FBDeviceModel(rawValue: "iPad mini 4")
  public static let modeliPadMini_5 = FBDeviceModel(rawValue: "iPad mini (5th generation)")
  public static let modelAppleTV = FBDeviceModel(rawValue: "Apple TV")
  public static let modelAppleTV4K = FBDeviceModel(rawValue: "Apple TV 4K")
  public static let modelAppleTV4KAt1080p = FBDeviceModel(rawValue: "Apple TV 4K (at 1080p)")
  public static let modelAppleWatch38mm = FBDeviceModel(rawValue: "Apple Watch - 38mm")
  public static let modelAppleWatch42mm = FBDeviceModel(rawValue: "Apple Watch - 42mm")
  public static let modelAppleWatchSE_40mm = FBDeviceModel(rawValue: "Apple Watch SE - 40mm")
  public static let modelAppleWatchSE_44mm = FBDeviceModel(rawValue: "Apple Watch SE - 44mm")
  public static let modelAppleWatchSeries2_38mm = FBDeviceModel(rawValue: "Apple Watch Series 2 - 38mm")
  public static let modelAppleWatchSeries2_42mm = FBDeviceModel(rawValue: "Apple Watch Series 2 - 42mm")
  public static let modelAppleWatchSeries3_38mm = FBDeviceModel(rawValue: "Apple Watch Series 3 - 38mm")
  public static let modelAppleWatchSeries3_42mm = FBDeviceModel(rawValue: "Apple Watch Series 3 - 42mm")
  public static let modelAppleWatchSeries4_40mm = FBDeviceModel(rawValue: "Apple Watch Series 4 - 40mm")
  public static let modelAppleWatchSeries4_44mm = FBDeviceModel(rawValue: "Apple Watch Series 4 - 44mm")
  public static let modelAppleWatchSeries5_40mm = FBDeviceModel(rawValue: "Apple Watch Series 5 - 40mm")
  public static let modelAppleWatchSeries5_44mm = FBDeviceModel(rawValue: "Apple Watch Series 5 - 44mm")
  public static let modelAppleWatchSeries6_40mm = FBDeviceModel(rawValue: "Apple Watch Series 6 - 40mm")
  public static let modelAppleWatchSeries6_44mm = FBDeviceModel(rawValue: "Apple Watch Series 6 - 44mm")
}

/// OS Versions Name Enumeration.
public struct FBOSVersionName: RawRepresentable, Hashable, Sendable {
  public let rawValue: String

  public init(rawValue: String) {
    self.rawValue = rawValue
  }

  public static let nameiOS_7_1 = FBOSVersionName(rawValue: "iOS 7.1")
  public static let nameiOS_8_0 = FBOSVersionName(rawValue: "iOS 8.0")
  public static let nameiOS_8_1 = FBOSVersionName(rawValue: "iOS 8.1")
  public static let nameiOS_8_2 = FBOSVersionName(rawValue: "iOS 8.2")
  public static let nameiOS_8_3 = FBOSVersionName(rawValue: "iOS 8.3")
  public static let nameiOS_8_4 = FBOSVersionName(rawValue: "iOS 8.4")
  public static let nameiOS_9_0 = FBOSVersionName(rawValue: "iOS 9.0")
  public static let nameiOS_9_1 = FBOSVersionName(rawValue: "iOS 9.1")
  public static let nameiOS_9_2 = FBOSVersionName(rawValue: "iOS 9.2")
  public static let nameiOS_9_3 = FBOSVersionName(rawValue: "iOS 9.3")
  public static let nameiOS_9_3_1 = FBOSVersionName(rawValue: "iOS 9.3.1")
  public static let nameiOS_9_3_2 = FBOSVersionName(rawValue: "iOS 9.3.2")
  public static let nameiOS_10_0 = FBOSVersionName(rawValue: "iOS 10.0")
  public static let nameiOS_10_1 = FBOSVersionName(rawValue: "iOS 10.1")
  public static let nameiOS_10_2 = FBOSVersionName(rawValue: "iOS 10.2")
  public static let nameiOS_10_3 = FBOSVersionName(rawValue: "iOS 10.3")
  public static let nameiOS_11_0 = FBOSVersionName(rawValue: "iOS 11.0")
  public static let nameiOS_11_1 = FBOSVersionName(rawValue: "iOS 11.1")
  public static let nameiOS_11_2 = FBOSVersionName(rawValue: "iOS 11.2")
  public static let nameiOS_11_3 = FBOSVersionName(rawValue: "iOS 11.3")
  public static let nameiOS_11_4 = FBOSVersionName(rawValue: "iOS 11.4")
  public static let nameiOS_12_0 = FBOSVersionName(rawValue: "iOS 12.0")
  public static let nameiOS_12_1 = FBOSVersionName(rawValue: "iOS 12.1")
  public static let nameiOS_12_2 = FBOSVersionName(rawValue: "iOS 12.2")
  public static let nameiOS_12_4 = FBOSVersionName(rawValue: "iOS 12.4")
  public static let nameiOS_13_0 = FBOSVersionName(rawValue: "iOS 13.0")
  public static let nameiOS_13_1 = FBOSVersionName(rawValue: "iOS 13.1")
  public static let nameiOS_13_2 = FBOSVersionName(rawValue: "iOS 13.2")
  public static let nameiOS_13_3 = FBOSVersionName(rawValue: "iOS 13.3")
  public static let nameiOS_13_4 = FBOSVersionName(rawValue: "iOS 13.4")
  public static let nameiOS_13_5 = FBOSVersionName(rawValue: "iOS 13.5")
  public static let nameiOS_14_0 = FBOSVersionName(rawValue: "iOS 14.0")
  public static let nameiOS_14_1 = FBOSVersionName(rawValue: "iOS 14.1")
  public static let nameiOS_14_2 = FBOSVersionName(rawValue: "iOS 14.2")
  public static let nameiOS_15_0 = FBOSVersionName(rawValue: "iOS 15.0")
  public static let nameiOS_15_1 = FBOSVersionName(rawValue: "iOS 15.1")
  public static let nameiOS_15_2 = FBOSVersionName(rawValue: "iOS 15.2")
  public static let nameiOS_15_3 = FBOSVersionName(rawValue: "iOS 15.3")
  public static let nameiOS_15_4 = FBOSVersionName(rawValue: "iOS 15.4")
  public static let nameiOS_15_5 = FBOSVersionName(rawValue: "iOS 15.5")
  public static let nameiOS_16_0 = FBOSVersionName(rawValue: "iOS 16.0")
  public static let nameiOS_16_1 = FBOSVersionName(rawValue: "iOS 16.1")
  public static let nameiOS_16_2 = FBOSVersionName(rawValue: "iOS 16.2")
  public static let nameiOS_16_3 = FBOSVersionName(rawValue: "iOS 16.3")
  public static let nameiOS_16_4 = FBOSVersionName(rawValue: "iOS 16.4")
  public static let nameiOS_16_5 = FBOSVersionName(rawValue: "iOS 16.5")
  public static let nameiOS_16_6 = FBOSVersionName(rawValue: "iOS 16.6")
  public static let nameiOS_16_7 = FBOSVersionName(rawValue: "iOS 16.7")
  public static let nameiOS_17_0 = FBOSVersionName(rawValue: "iOS 17.0")
  public static let nameiOS_17_1 = FBOSVersionName(rawValue: "iOS 17.1")
  public static let nameiOS_17_2 = FBOSVersionName(rawValue: "iOS 17.2")
  public static let nameiOS_17_3 = FBOSVersionName(rawValue: "iOS 17.3")
  public static let nameiOS_17_4 = FBOSVersionName(rawValue: "iOS 17.4")
  public static let nameiOS_17_5 = FBOSVersionName(rawValue: "iOS 17.5")
  public static let nameiOS_17_6 = FBOSVersionName(rawValue: "iOS 17.6")
  public static let nameiOS_17_7 = FBOSVersionName(rawValue: "iOS 17.7")
  public static let nameiOS_18_0 = FBOSVersionName(rawValue: "iOS 18.0")
  public static let nameiOS_18_1 = FBOSVersionName(rawValue: "iOS 18.1")
  public static let nameiOS_18_2 = FBOSVersionName(rawValue: "iOS 18.2")
  public static let nameiOS_18_3 = FBOSVersionName(rawValue: "iOS 18.3")
  public static let nameiOS_18_4 = FBOSVersionName(rawValue: "iOS 18.4")
  public static let nameiOS_18_5 = FBOSVersionName(rawValue: "iOS 18.5")
  public static let nameiOS_18_6 = FBOSVersionName(rawValue: "iOS 18.6")
  public static let nameiOS_18_7 = FBOSVersionName(rawValue: "iOS 18.7")
  public static let nameiOS_26_0 = FBOSVersionName(rawValue: "iOS 26.0")
  public static let nameiOS_26_1 = FBOSVersionName(rawValue: "iOS 26.1")
  public static let nameiOS_26_2 = FBOSVersionName(rawValue: "iOS 26.2")
  public static let nameiOS_26_3 = FBOSVersionName(rawValue: "iOS 26.3")
  public static let nameiOS_26_4 = FBOSVersionName(rawValue: "iOS 26.4")
  public static let nametvOS_9_0 = FBOSVersionName(rawValue: "tvOS 9.0")
  public static let nametvOS_9_1 = FBOSVersionName(rawValue: "tvOS 9.1")
  public static let nametvOS_9_2 = FBOSVersionName(rawValue: "tvOS 9.2")
  public static let nametvOS_10_0 = FBOSVersionName(rawValue: "tvOS 10.0")
  public static let nametvOS_10_1 = FBOSVersionName(rawValue: "tvOS 10.1")
  public static let nametvOS_10_2 = FBOSVersionName(rawValue: "tvOS 10.2")
  public static let nametvOS_11_0 = FBOSVersionName(rawValue: "tvOS 11.0")
  public static let nametvOS_11_1 = FBOSVersionName(rawValue: "tvOS 11.1")
  public static let nametvOS_11_2 = FBOSVersionName(rawValue: "tvOS 11.2")
  public static let nametvOS_11_3 = FBOSVersionName(rawValue: "tvOS 11.3")
  public static let nametvOS_11_4 = FBOSVersionName(rawValue: "tvOS 11.4")
  public static let nametvOS_12_0 = FBOSVersionName(rawValue: "tvOS 12.0")
  public static let nametvOS_12_1 = FBOSVersionName(rawValue: "tvOS 12.1")
  public static let nametvOS_12_2 = FBOSVersionName(rawValue: "tvOS 12.2")
  public static let nametvOS_12_4 = FBOSVersionName(rawValue: "tvOS 12.4")
  public static let nametvOS_13_0 = FBOSVersionName(rawValue: "tvOS 13.0")
  public static let nametvOS_13_2 = FBOSVersionName(rawValue: "tvOS 13.2")
  public static let nametvOS_13_3 = FBOSVersionName(rawValue: "tvOS 13.3")
  public static let nametvOS_13_4 = FBOSVersionName(rawValue: "tvOS 13.4")
  public static let nametvOS_14_0 = FBOSVersionName(rawValue: "tvOS 14.0")
  public static let nametvOS_14_1 = FBOSVersionName(rawValue: "tvOS 14.1")
  public static let nametvOS_14_2 = FBOSVersionName(rawValue: "tvOS 14.2")
  public static let nametvOS_14_3 = FBOSVersionName(rawValue: "tvOS 14.3")
  public static let nametvOS_14_4 = FBOSVersionName(rawValue: "tvOS 14.4")
  public static let nametvOS_14_5 = FBOSVersionName(rawValue: "tvOS 14.5")
  public static let nametvOS_14_6 = FBOSVersionName(rawValue: "tvOS 14.6")
  public static let nametvOS_14_7 = FBOSVersionName(rawValue: "tvOS 14.7")
  public static let nametvOS_15_0 = FBOSVersionName(rawValue: "tvOS 15.0")
  public static let nametvOS_15_1 = FBOSVersionName(rawValue: "tvOS 15.1")
  public static let nametvOS_15_2 = FBOSVersionName(rawValue: "tvOS 15.2")
  public static let nametvOS_15_3 = FBOSVersionName(rawValue: "tvOS 15.3")
  public static let nametvOS_15_4 = FBOSVersionName(rawValue: "tvOS 15.4")
  public static let nametvOS_15_5 = FBOSVersionName(rawValue: "tvOS 15.5")
  public static let nametvOS_15_6 = FBOSVersionName(rawValue: "tvOS 15.6")
  public static let nametvOS_16_0 = FBOSVersionName(rawValue: "tvOS 16.0")
  public static let nametvOS_16_1 = FBOSVersionName(rawValue: "tvOS 16.1")
  public static let nametvOS_16_2 = FBOSVersionName(rawValue: "tvOS 16.2")
  public static let nametvOS_16_3 = FBOSVersionName(rawValue: "tvOS 16.3")
  public static let nametvOS_16_4 = FBOSVersionName(rawValue: "tvOS 16.4")
  public static let nametvOS_16_5 = FBOSVersionName(rawValue: "tvOS 16.5")
  public static let nametvOS_16_6 = FBOSVersionName(rawValue: "tvOS 16.6")
  public static let nametvOS_17_0 = FBOSVersionName(rawValue: "tvOS 17.0")
  public static let nametvOS_17_1 = FBOSVersionName(rawValue: "tvOS 17.1")
  public static let nametvOS_17_2 = FBOSVersionName(rawValue: "tvOS 17.2")
  public static let nametvOS_17_3 = FBOSVersionName(rawValue: "tvOS 17.3")
  public static let nametvOS_17_4 = FBOSVersionName(rawValue: "tvOS 17.4")
  public static let nametvOS_17_5 = FBOSVersionName(rawValue: "tvOS 17.5")
  public static let nametvOS_17_6 = FBOSVersionName(rawValue: "tvOS 17.6")
  public static let nametvOS_18_0 = FBOSVersionName(rawValue: "tvOS 18.0")
  public static let nametvOS_18_1 = FBOSVersionName(rawValue: "tvOS 18.1")
  public static let nametvOS_18_2 = FBOSVersionName(rawValue: "tvOS 18.2")
  public static let nametvOS_18_3 = FBOSVersionName(rawValue: "tvOS 18.3")
  public static let nametvOS_18_4 = FBOSVersionName(rawValue: "tvOS 18.4")
  public static let nametvOS_18_5 = FBOSVersionName(rawValue: "tvOS 18.5")
  public static let nametvOS_18_6 = FBOSVersionName(rawValue: "tvOS 18.6")
  public static let nametvOS_26_0 = FBOSVersionName(rawValue: "tvOS 26.0")
  public static let nametvOS_26_1 = FBOSVersionName(rawValue: "tvOS 26.1")
  public static let nametvOS_26_2 = FBOSVersionName(rawValue: "tvOS 26.2")
  public static let nametvOS_26_3 = FBOSVersionName(rawValue: "tvOS 26.3")
  public static let nametvOS_26_4 = FBOSVersionName(rawValue: "tvOS 26.4")
  public static let namewatchOS_2_0 = FBOSVersionName(rawValue: "watchOS 2.0")
  public static let namewatchOS_2_1 = FBOSVersionName(rawValue: "watchOS 2.1")
  public static let namewatchOS_2_2 = FBOSVersionName(rawValue: "watchOS 2.2")
  public static let namewatchOS_3_0 = FBOSVersionName(rawValue: "watchOS 3.0")
  public static let namewatchOS_3_1 = FBOSVersionName(rawValue: "watchOS 3.1")
  public static let namewatchOS_3_2 = FBOSVersionName(rawValue: "watchOS 3.2")
  public static let namewatchOS_4_0 = FBOSVersionName(rawValue: "watchOS 4.0")
  public static let namewatchOS_4_1 = FBOSVersionName(rawValue: "watchOS 4.1")
  public static let namewatchOS_4_2 = FBOSVersionName(rawValue: "watchOS 4.2")
  public static let namewatchOS_5_0 = FBOSVersionName(rawValue: "watchOS 5.0")
  public static let namewatchOS_5_1 = FBOSVersionName(rawValue: "watchOS 5.1")
  public static let namewatchOS_5_2 = FBOSVersionName(rawValue: "watchOS 5.2")
  public static let namewatchOS_5_3 = FBOSVersionName(rawValue: "watchOS 5.3")
  public static let namewatchOS_6_0 = FBOSVersionName(rawValue: "watchOS 6.0")
  public static let namewatchOS_6_1 = FBOSVersionName(rawValue: "watchOS 6.1")
  public static let namewatchOS_6_2 = FBOSVersionName(rawValue: "watchOS 6.2")
  public static let namewatchOS_7_0 = FBOSVersionName(rawValue: "watchOS 7.0")
  public static let namewatchOS_7_1 = FBOSVersionName(rawValue: "watchOS 7.1")
  public static let namewatchOS_7_2 = FBOSVersionName(rawValue: "watchOS 7.2")
  public static let namewatchOS_7_3 = FBOSVersionName(rawValue: "watchOS 7.3")
  public static let namewatchOS_7_4 = FBOSVersionName(rawValue: "watchOS 7.4")
  public static let namewatchOS_7_5 = FBOSVersionName(rawValue: "watchOS 7.5")
  public static let namewatchOS_7_6 = FBOSVersionName(rawValue: "watchOS 7.6")
  public static let namewatchOS_8_0 = FBOSVersionName(rawValue: "watchOS 8.0")
  public static let namewatchOS_8_1 = FBOSVersionName(rawValue: "watchOS 8.1")
  public static let namewatchOS_8_2 = FBOSVersionName(rawValue: "watchOS 8.2")
  public static let namewatchOS_8_3 = FBOSVersionName(rawValue: "watchOS 8.3")
  public static let namewatchOS_8_4 = FBOSVersionName(rawValue: "watchOS 8.4")
  public static let namewatchOS_8_5 = FBOSVersionName(rawValue: "watchOS 8.5")
  public static let namewatchOS_8_6 = FBOSVersionName(rawValue: "watchOS 8.6")
  public static let namewatchOS_8_7 = FBOSVersionName(rawValue: "watchOS 8.7")
  public static let namewatchOS_8_8 = FBOSVersionName(rawValue: "watchOS 8.8")
  public static let namewatchOS_9_0 = FBOSVersionName(rawValue: "watchOS 9.0")
  public static let namewatchOS_9_1 = FBOSVersionName(rawValue: "watchOS 9.1")
  public static let namewatchOS_9_2 = FBOSVersionName(rawValue: "watchOS 9.2")
  public static let namewatchOS_9_3 = FBOSVersionName(rawValue: "watchOS 9.3")
  public static let namewatchOS_9_4 = FBOSVersionName(rawValue: "watchOS 9.4")
  public static let namewatchOS_9_5 = FBOSVersionName(rawValue: "watchOS 9.5")
  public static let namewatchOS_9_6 = FBOSVersionName(rawValue: "watchOS 9.6")
  public static let namewatchOS_10_0 = FBOSVersionName(rawValue: "watchOS 10.0")
  public static let namewatchOS_10_1 = FBOSVersionName(rawValue: "watchOS 10.1")
  public static let namewatchOS_10_2 = FBOSVersionName(rawValue: "watchOS 10.2")
  public static let namewatchOS_10_3 = FBOSVersionName(rawValue: "watchOS 10.3")
  public static let namewatchOS_10_4 = FBOSVersionName(rawValue: "watchOS 10.4")
  public static let namewatchOS_10_5 = FBOSVersionName(rawValue: "watchOS 10.5")
  public static let namewatchOS_10_6 = FBOSVersionName(rawValue: "watchOS 10.6")
  public static let namewatchOS_11_0 = FBOSVersionName(rawValue: "watchOS 11.0")
  public static let namewatchOS_11_1 = FBOSVersionName(rawValue: "watchOS 11.1")
  public static let namewatchOS_11_2 = FBOSVersionName(rawValue: "watchOS 11.2")
  public static let namewatchOS_11_3 = FBOSVersionName(rawValue: "watchOS 11.3")
  public static let namewatchOS_11_4 = FBOSVersionName(rawValue: "watchOS 11.4")
  public static let namewatchOS_11_5 = FBOSVersionName(rawValue: "watchOS 11.5")
  public static let namewatchOS_11_6 = FBOSVersionName(rawValue: "watchOS 11.6")
  public static let namewatchOS_26_0 = FBOSVersionName(rawValue: "watchOS 26.0")
  public static let namewatchOS_26_1 = FBOSVersionName(rawValue: "watchOS 26.1")
  public static let namewatchOS_26_2 = FBOSVersionName(rawValue: "watchOS 26.2")
  public static let namewatchOS_26_3 = FBOSVersionName(rawValue: "watchOS 26.3")
  public static let namewatchOS_26_4 = FBOSVersionName(rawValue: "watchOS 26.4")
  public static let namemac = FBOSVersionName(rawValue: "macOS")
}
