#!/usr/bin/env python3
"""File and line census of the package, written as Markdown to stdout. LOC = physical lines."""
import os, subprocess, sys
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(root)
files = subprocess.run(['git', 'ls-files'], capture_output=True, text=True, check=True).stdout.split()
kinds = {'.swift': 'Swift', '.m': 'ObjC .m', '.c': 'C', '.h': 'Headers', '.tbd': '.tbd'}
areas = {}
for f in files:
    ext = os.path.splitext(f)[1]
    if ext not in kinds:
        continue
    parts = f.split('/')
    area = '/'.join(parts[:2]) if parts[0] in ('Sources', 'Tests') else parts[0]
    lines = sum(1 for _ in open(f, 'rb'))
    counts = areas.setdefault(area, {})
    n, loc = counts.get(kinds[ext], (0, 0))
    counts[kinds[ext]] = (n + 1, loc + lines)
head = ['Swift', 'ObjC .m', 'C', 'Headers', '.tbd']
commit = subprocess.run(['git', 'rev-parse', '--short', 'HEAD'], capture_output=True, text=True).stdout.strip()
print(f'# Package census (taptaptap {commit})\n')
print('Generated by `scripts/census.py` from tracked files. Each cell: files / physical lines.\n')
print('| Area | ' + ' | '.join(head) + ' |')
print('|---|' + '---|' * len(head))
totals = {}
for area in sorted(areas):
    row = []
    for h in head:
        n, loc = areas[area].get(h, (0, 0))
        t = totals.get(h, (0, 0)); totals[h] = (t[0] + n, t[1] + loc)
        row.append(f'{n} / {loc}' if n else '')
    print(f'| {area} | ' + ' | '.join(row) + ' |')
print('| **Total** | ' + ' | '.join(f'{totals.get(h,(0,0))[0]} / {totals.get(h,(0,0))[1]}' for h in head) + ' |')
